### ISSUE TITLE
build failed with go1.19

### ISSUE THREAD

**Issue by aytrack** [pingcap/TiProxy#105]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. go version 1.19 on mac 
2. pull and make

### 2. What did you expect to see? (Required)
build success
### 3. What did you see instead (Required)
build failed
```sql
go build  -gcflags '' -ldflags '' -tags '' -o ./bin/tiproxy ./cmd/tiproxy
# github.com/pingcap/TiProxy/pkg/manager/config
<autogenerated>:1: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
make: *** [cmd_tiproxy] Error 2                                                      
```
before https://github.com/pingcap/TiProxy/pull/95 it can build success.
### 4. What is your version? (Required)
```
go version go1.19 darwin/amd64   
```
main 6a218a13cea4f056638509465f2a

**Comment by xhebox** [comment]
Maybe update 1.19.1, I have no issues compiling it on mac. And I can only debug it after the vacation. My M1 is in the company.

**Comment by aytrack** [comment]
> Maybe update 1.19.1, I have no issues compiling it on mac. And I can only debug it after the vacation. My M1 is in the company.

After update the go version, it works for me. close this issue.
