### ISSUE TITLE
require_secure_transport not works while using tiproxy

### ISSUE THREAD

**Issue by aytrack** [pingcap/tiproxy#124]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy tidb cluster and tiproxy
2. create user with require_secure_transport `create user u1 require ssl;`
3. connect the tiproxy with  `--ssl-mode=DISABLED `
```bash
mysql -u u1 -h 127.0.0.1 -P 6000 -p --ssl-mode=DISABLED 
```

### 2. What did you expect to see? (Required)
report error ERROR 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.    
### 3. What did you see instead (Required)
connect the server success and not in ssl
```sql
mysql> \s
--------------
mysql  Ver 8.0.22 for osx10.15 on x86_64 (Homebrew)

Connection id:          100
Current database:
Current user:           u1@100.64.10.62
SSL:                    Not in use
Current pager:          less
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.25-TiDB-None TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible
Protocol version:       10
Connection:             127.0.0.1 via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
TCP port:               6001
Binary data as:         Hexadecimal
Uptime:                 53 min 1 sec

Threads: 0  Questions: 0  Slow queries: 0  Opens: 0  Flush tables: 0  Open tables: 0  Queries per second avg: 0.000
--------------
```
### 4. What is your version? (Required)
master 80ff9106fd759a4e2be69d4ac353

**Comment by djshow832** [comment]
Fixed by https://github.com/pingcap/tiproxy/pull/303
