### ISSUE TITLE
Optimize backoff for connecting to backends

### ISSUE THREAD

**Issue by djshow832** [pingcap/tiproxy#189]
## Development Task

In #172, the backoff mechanism is changed: it tries all the backends all at once, and then waits and retries.
If the first backend which the gateway returns is down, then all connections will wait for 200ms, this is slow.

**Comment by xhebox** [comment]
But we have a dial of 2s, does it really matter to add another `1/10` duration? Maybe we could use `backoff.ExponentialBackOff`.

**Comment by djshow832** [comment]
> But we have a dial timeout of 2s

In many cases, `Dial` returns immediately if the target is down.

> IMO, this only makes sense, if 2nd connection is healthy

If we use `ExponentialBackOff`, then it will be faster even if the 2nd connection is unhealthy. If most of them are unhealthy,  the speed doesn't matter.
