### ISSUE TITLE
Use epoll

### ISSUE THREAD

**Issue by xhebox** [pingcap/tiproxy#248]
## Goal

1. reduce goroutine number
2. avoid buffer copying
3.  The current backend must convert from `*PacketIO` oriented to `[]byte/MysqlPacket` oriented. Command processor or authenticator should not read from the connection actively. To do this, we should provide a set of helper parsing/making packets.

Lots of refactors are needed, since blocking & non-blocking code will be totally different.

**Comment by dveeden** [comment]
Might be good to consider io_uring as well. Not sure which one is better.

**Comment by xhebox** [comment]
> Might be good to consider io_uring as well. Not sure which one is better.

Sounds good. But I am not aware of any golang io_uring implementation. And it requires a pretty new kernel support...

**Comment by dveeden** [comment]
I found these:
- https://pkg.go.dev/github.com/iceber/iouring-go
- https://developers.mattermost.com/blog/hands-on-iouring-go/

And while io_uring looks interesting there are some tests that don't show a clear winner:
- https://www.alibabacloud.com/blog/io-uring-vs--epoll-which-is-better-in-network-programming_599544
- https://github.com/axboe/liburing/issues/536

So this may or may not be the right choice.

**Comment by djshow832** [comment]
Tested gnet and netpoll. Both perform worse than go net because EpollWait runs more frequently.
io_uring is not mature enough and is barely used in mission-critical software, so I won't consider it shortly.
