### ISSUE TITLE
Balance by real tidb connections

### ISSUE THREAD

**Issue by xhebox** [pingcap/tiproxy#254]
## Development Task

On TiDB cloud, or aws, you are given one DNS name corresponding to multiple IPs, which re LB/NAT servers.

However, it is decided by clients' computer/os that which IP should be used to establish TCP connections.

This leads to a problem that connections are only balanced roughly on each router of tiproxy. We can have the following cases:

```
tiproxy-0: 8 tidb-0, 10 tidb-1.
tiproxy-1: 12 tidb-0, 14 tidb-1.
tiproxy-2: 30 tidb-0, 33 tidb-1.
```

This accumulated to `50 tidb-0` and `57 tidb-1`, with 7 connections unbalanced, resuling into unbalanced load temporarily.

Some more complex happens when:

```
tiproxy-0: 10 tidb-0, 8 tidb-1.
tiproxy-1: 10 tidb-0, 14 tidb-1.
```

Overall we have higher load on `tidb-1`. When `tiproxy-1` are trying to migrate `tidb-1 => tidb-0`, `tiproxy-1` may migrate `tidb-0 >= tidb-1`, which will give `tidb-1` even more load.

Maybe it is better to balance by real tidb connection numbers. Because migration only keeps tiproxy and tidb busy, but don't reduce the load of tiproxy.

**Comment by djshow832** [comment]
We're going to balance by CPU usage, so close this one.
