### ISSUE TITLE
TiProxy infinitely reloads the config file

### ISSUE THREAD

**Issue by djshow832** [pingcap/TiProxy#321]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use the config file in the working directory.

```sh
cp conf/proxy.toml .
./bin/tiproxy --config=proxy.toml > proxy.log
```

### 2. What did you expect to see? (Required)

The file size of `proxy.log` is small.

### 3. What did you see instead (Required)

The file size of `proxy.log` keeps increasing rapidly. The logs are all about reloading the config file.
The event of the config file is `event="WRITE         \"proxy.log\""`, which means the log file is modified but the config file is not.

### 4. What is your version? (Required)

master

OS: macOS

**Comment by xhebox** [comment]
In fact, it is expected. Config file should be located at a separate directory.

**Comment by djshow832** [comment]
> In fact, it is expected. Config file should be located at a separate directory.

I don't think it's common sense for everyone. For example, in the tidb-test, the config file and log file are in the same directory. It just redirects the output to the current directory so that the log file is overwritten for every run and avoids removal.

**Comment by djshow832** [comment]
> > > In fact, it is expected. Config file should be located at a separate directory.
> > 
> > 
> > I don't think it's common sense for everyone. For example, in the tidb-test, the config file and log file are in the same directory. It just redirects the output to the current directory so that the log file is overwritten for every run and avoids removal.
> 
> I understand. But, then, reloading conigs on k8s becomes difficult if you correct this behavior. I guess the only way to fix is filtering config file on the event again..

2 methods:
- Watch the remove, rename, and create events on the directory and write events on the file.
- Filter the file name when the event is triggered. I choose this one because it's easier.

I'm filing the PR.
