### ISSUE TITLE
support make clean option

### ISSUE THREAD

**Issue by shawn0915** [pingcap/TiProxy#343]
### Describe the feature you'd like

please support `make clean` option.

currently:
```
$ git lg
* b944a8f - (grafted, HEAD -> main, origin/main, origin/HEAD) fix: remove mirrot test (#339) (5 days ago) <xhe>
$ make clean
make: *** No rule to make target `clean'.  Stop.
```

**Comment by xhebox** [comment]
What is the expected behavior of clean? Give more descriptions.

**Comment by shawn0915** [comment]
if compiling interrupts  (`^Cmake: *** [lint] Interrupt
`), we can use `make clean` to clean up legacy files. 
or clean up binary files, so that we can compile again without removing the current directory and git clone again.  like what we do in tiup.  https://github.com/pingcap/tiup/blob/master/Makefile#L102C1-L106C47
