### ISSUE TITLE
`Connection id` always `100`

### ISSUE THREAD

**Issue by shawn0915** [pingcap/TiProxy#345]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

might related this : 
https://github.com/pingcap/TiProxy/blob/main/pkg/proxy/net/mysql.go#L26
```
ConnID        = 100 --> hard?
```

### 3. What did you see instead (Required)
![图片](https://github.com/pingcap/TiProxy/assets/17957066/770e2e60-0d8c-46ec-bb1e-7c746bf179fc)

### 4. What is your version? (Required)

main

**Comment by djshow832** [comment]
It's impossible to send the right TiDB connection ID to the client:
- TiProxy sends the connection ID, receives the response packet, and then handshakes with TiDB.
- The TiDB connection ID in the handshake packet is truncated. It's actually 8 bytes but only sends 4 bytes.

But I think it's fine to send a TiProxy connection ID to the client. This connection ID is different with TiDB connection ID, but it should be fine.

**Comment by xhebox** [comment]
> But I think it's fine to send a TiProxy connection ID to the client. This connection ID is different with TiDB connection ID, but it should be fine.

Yeah, we can  send a real connection id that is not fixed.
