### ISSUE TITLE
Inconsistent version when using TiProxy with TiDB v7.5.0 or newer

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiproxy#438]
## Bug Report

Use TiProxy with TiDB v7.5.0 or newer

### 1. Minimal reproduce step (Required)

![image](https://github.com/pingcap/tidb/assets/1272980/a0c09c16-393a-4ddf-baa8-da58384a1582)

### 2. What did you expect to see? (Required)

Both `status` and `SELECT VERSION()` to report the same version.

### 3. What did you see instead (Required)

See screenshot

### 4. What is your TiDB version? (Required)

v7.5.0

Some ways to fix this:

- Update `github.com/pingcap/tidb/parser` (but then using this with older versions will have a similar issue)
- Connect to one of the backend servers to get a version
  - Use something like `$ curl -s http://127.0.0.1:10080/status |jq .version`
  - Maybe the first server? Maybe a random server? Maybe all of them and then use the highest or lowest?
- Store this in PD/etcd and have TiDB or PD set this.

**Comment by djshow832** [comment]
We are currently using the version of a random server, refer to #281.
Maybe it doesn't work well? I'll look into it.

**Comment by djshow832** [comment]
I can't reproduce it with `tiup playground v7.5.0 --tiproxy 1 --tiproxy.version nightly --tiflash 0`.

```
$ mysql -h127.1 -uroot -P6000 test
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 8.0.11-TiDB-v7.5.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> status
--------------
mysql  Ver 8.1.0 for macos12.6 on x86_64 (Homebrew)

Connection id:          1
Current database:       test
Current user:           root@127.0.0.1
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         8.0.11-TiDB-v7.5.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible
Protocol version:       10
Connection:             127.1 via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
TCP port:               6000
Binary data as:         Hexadecimal
Uptime:                 21 sec

Threads: 0  Questions: 0  Slow queries: 0  Opens: 0  Flush tables: 0  Open tables: 0  Queries per second avg: 0.000
--------------

```

Can I know how did you deploy the cluster and what's the TiProxy version?

**Comment by dveeden** [comment]
Looks like this is what happened:
