### ISSUE TITLE
migrate_duration_seconds metric labels keep on increasing

### ISSUE THREAD

**Issue by salarali** [pingcap/tiproxy#582]
## Bug Report

I have auto scaling enabled for the tidb servers. They come up and down based on requests. The metric labels for this metric keep on increasing because stale servers arent removed. I have tiproxy running for a few weeks and it got to the stage where the metrics volume got so huge that pulling from prometheus started failing.

I think this also applies to all the metrics defined here: https://github.com/pingcap/tiproxy/blob/1ace159e624625f71a373c56e8ddf014e050c421/pkg/metrics/balance.go#L43

**Comment by djshow832** [comment]
Indeed, the metric label includes the tidb server address and it increases when the number of servers increases. I didn't expect that the servers would change so frequently. I'll find a way to clear the retired tidb servers.
