### ISSUE TITLE
Prometheus config

### ISSUE THREAD

**Issue by salarali** [pingcap/tiproxy#607]
For balance to work properly, you need to setup prometheus access. I am unsure how to set this up? Is this setup in PD or somewhere else? Can someone point me towards how tiproxy will get the prometheus it will fetch the metrics from?

**Comment by djshow832** [comment]
If you're using TiUP or TiDB-Operator to deploy, just set the spec.
TiUP: https://docs.pingcap.com/tidb/dev/tiup-cluster-topology-reference#monitoring_servers
TiDB-Operator: https://docs.pingcap.com/tidb-in-kubernetes/stable/monitor-a-tidb-cluster

It's complex to deploy it manually: https://docs.pingcap.com/tidb/dev/deploy-monitoring-services

The good news is, I'm trying to read TiDB metrics without Prometheus. It will be released in the next version after about one month.

**Comment by djshow832** [comment]
I'm afraid the address is updated by TiUP and TiDB-Operator.

E.g. https://github.com/pingcap/tiup/blob/v1.16.0/pkg/cluster/task/update_topology.go#L126

If the address of Prometheus is fixed, you can update the address to ETCD in PD manually. The key is `/topology/prometheus` and the value is https://github.com/pingcap/tiup/blob/v1.16.0/pkg/cluster/task/update_topology.go#L97 in a JSON format.

If it's not urgent, I suggest you wait for the next TiProxy release.
